name: Build and Deploy Docker Application

on: [push]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Start SSH agent
      run: eval "$(ssh-agent -s)"

    - name: Add SSH key
      run: |
        echo "$SSH_PRIVATE_KEY" > /tmp/private.pem
        chmod 600 /tmp/private.pem
        ssh-add /tmp/private.pem
        rm /tmp/private.pem

    - name: Build Docker image
      run: sudo docker build -t my-nginx-app:latest .
      
    - name: Deploy Docker container
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        echo "$SSH_PRIVATE_KEY" | ssh-add -
        ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "
          docker stop my-nginx-app-container || true &&
          docker rm my-nginx-app-container || true &&
          docker run -d --name my-nginx-app-container -p 80:80 my-nginx-app:latest
        "
