name: Deploy Docker Application

on: [push]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: sudo docker build -t myapp:latest .

    - name: Log in to VM and deploy Docker container
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        echo "$SSH_PRIVATE_KEY" | ssh-add -
        ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "
          sudo docker pull myapp:latest &&
          sudo docker stop myapp-container || true &&
          sudo docker rm myapp-container || true &&
          sudo docker run -d --name myapp-container -p 80:80 myapp:latest
        "
